sudo: false
language: go
go:
- 1.7

install:
  - go get
  - go get github.com/mitchellh/gox  
script:
  # build for all platforms with gox
  - gox -arch="amd64" -os="darwin linux windows" -output "dist/{{.OS}}-{{.Arch}}/{{.Dir}}" .
  # create one archive per platform
  - zip -j packer-post-processor-vagrant-s3-${TRAVIS_TAG}-darwin-amd64.zip ./dist/darwin-amd64/*
  - zip -j packer-post-processor-vagrant-s3-${TRAVIS_TAG}-linux-amd64.zip ./dist/linux-amd64/*
  - zip -j packer-post-processor-vagrant-s3-${TRAVIS_TAG}-windows-amd64.zip ./dist/windows-amd64/*
deploy:
  provider: releases
  api_key:
    secure: gdpfaNRcBOmy6m+mIFW0cGOGbZwe30cuth7tWe0CGIoKyBTz6x5oo+0ErD6L3phYQij9ltXHKJ0/aA4U57KlVU1OUn6HhweqHHmtuh1/bKl0pxxyWciN1WxDz/50/ZtQUez7J94gqOvPHk6DmPd5EKJcLUJIwb45CpNHmbiS7I8=
  file:
    - packer-post-processor-vagrant-s3-${TRAVIS_TAG}-darwin-amd64.zip
    - packer-post-processor-vagrant-s3-${TRAVIS_TAG}-darwin-amd64.zip
    - packer-post-processor-vagrant-s3-${TRAVIS_TAG}-windows-amd64.zip
  on:
    repo: lmars/packer-post-processor-vagrant-s3
